import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Noto_Sans_KR } from 'next/font/google';
import { PropsWithChildren } from 'react';
import './globals.css';

const notoSansKr = Noto_Sans_KR({
  weight: ['300', '400', '500', '600', '700'],
  display: 'fallback',
  fallback: [
    // 디자이너분과 상의한 폴백 폰트 넣으시면 됩니다
    '-apple-system',
    'Apple SD Gothic Neo',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'sans-serif',
  ],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>{children}</body>
    </html>
  );
}
