import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Noto_Sans_KR } from 'next/font/google';
import { PropsWithChildren } from 'react';
import './globals.css';
import Registry from '@components/Registry';
import GlobalStyle from '@components/GlobalStyle';

const notoSansKr = Noto_Sans_KR({
  weight: ['300', '400', '500', '600', '700'],
  display: 'auto',
  fallback: [
    '-apple-system',
    'Apple SD Gothic Neo',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'sans-serif',
  ],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <Registry>
          <GlobalStyle />
          {children}
        </Registry>
      </body>
    </html>
  );
}
