import type { Metadata } from 'next';
import FONT from '@src/app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="kr"
      className={`${FONT.bold.variable} ${FONT.medium.variable} ${FONT.light.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
